
package jaxws.metro.client3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PredictionsSOAP", targetNamespace = "http://example2.jaxws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PredictionsSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.DeleteResponse")
    @Action(input = "http://example2.jaxws/PredictionsSOAP/deleteRequest", output = "http://example2.jaxws/PredictionsSOAP/deleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws VerbosityException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.CreateResponse")
    @Action(input = "http://example2.jaxws/PredictionsSOAP/createRequest", output = "http://example2.jaxws/PredictionsSOAP/createResponse", fault = {
        @FaultAction(className = VerbosityException_Exception.class, value = "http://example2.jaxws/PredictionsSOAP/create/Fault/VerbosityException")
    })
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws VerbosityException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<jaxws.metro.client3.Prediction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.GetAllResponse")
    @Action(input = "http://example2.jaxws/PredictionsSOAP/getAllRequest", output = "http://example2.jaxws/PredictionsSOAP/getAllResponse")
    public List<Prediction> getAll();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws VerbosityException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "edit", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.EditResponse")
    @Action(input = "http://example2.jaxws/PredictionsSOAP/editRequest", output = "http://example2.jaxws/PredictionsSOAP/editResponse", fault = {
        @FaultAction(className = VerbosityException_Exception.class, value = "http://example2.jaxws/PredictionsSOAP/edit/Fault/VerbosityException")
    })
    public String edit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws VerbosityException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns jaxws.metro.client3.Prediction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOne", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.GetOne")
    @ResponseWrapper(localName = "getOneResponse", targetNamespace = "http://example2.jaxws/", className = "jaxws.metro.client3.GetOneResponse")
    @Action(input = "http://example2.jaxws/PredictionsSOAP/getOneRequest", output = "http://example2.jaxws/PredictionsSOAP/getOneResponse")
    public Prediction getOne(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
