
package jaxws.metro.client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandImplService", targetNamespace = "http://example1.jaxws/", wsdlLocation = "http://localhost:8080/JaxWsMetroWebApp/rs?wsdl")
public class RandImplService
    extends Service
{

    private final static URL RANDIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDIMPLSERVICE_EXCEPTION;
    private final static QName RANDIMPLSERVICE_QNAME = new QName("http://example1.jaxws/", "RandImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JaxWsMetroWebApp/rs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDIMPLSERVICE_WSDL_LOCATION = url;
        RANDIMPLSERVICE_EXCEPTION = e;
    }

    public RandImplService() {
        super(__getWsdlLocation(), RANDIMPLSERVICE_QNAME);
    }

    public RandImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDIMPLSERVICE_QNAME, features);
    }

    public RandImplService(URL wsdlLocation) {
        super(wsdlLocation, RANDIMPLSERVICE_QNAME);
    }

    public RandImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDIMPLSERVICE_QNAME, features);
    }

    public RandImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RandService
     */
    @WebEndpoint(name = "RandImplPort")
    public RandService getRandImplPort() {
        return super.getPort(new QName("http://example1.jaxws/", "RandImplPort"), RandService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandService
     */
    @WebEndpoint(name = "RandImplPort")
    public RandService getRandImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example1.jaxws/", "RandImplPort"), RandService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDIMPLSERVICE_EXCEPTION!= null) {
            throw RANDIMPLSERVICE_EXCEPTION;
        }
        return RANDIMPLSERVICE_WSDL_LOCATION;
    }

}
